export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as Loader } from './Loader'
export { default as Services } from './Services'
export { default as Welcome } from './Welcome'
export { default as FundingBody } from './FundingBody'
export { default as NavbarFundingDetail } from './NavbarFundingDetail'